# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hippie_banevasion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Byondversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('byondversion', models.IntegerField(max_length=4, unique=True)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
