# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hippie_banevasion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useragent',
            name='useragent_hash',
            field=models.CharField(default='', max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useragent',
            name='useragent',
            field=models.TextField(),
        ),
    ]
