# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hippie_banevasion', '0002_byondversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='byondversion',
            name='byondversion',
            field=models.IntegerField(unique=True),
        ),
    ]
