# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hippie_banevasion', '0003_auto_20170327_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ckey', models.CharField(max_length=255, unique=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now_add=True)),
                ('byondversions', models.ManyToManyField(to='hippie_banevasion.ByondVersion')),
            ],
        ),
        migrations.CreateModel(
            name='ClientBlob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='fingerprints',
            field=models.ManyToManyField(to='hippie_banevasion.ClientBlob'),
        ),
        migrations.AddField(
            model_name='client',
            name='related_accounts',
            field=models.ManyToManyField(related_name='_client_related_accounts_+', to='hippie_banevasion.Client'),
        ),
        migrations.AddField(
            model_name='client',
            name='useragents',
            field=models.ManyToManyField(to='hippie_banevasion.Useragent'),
        ),
    ]
