# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hippie_banevasion', '0006_auto_20170329_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='last_post',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='byond_versions',
            field=models.ManyToManyField(to='hippie_banevasion.ByondVersion'),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_seen',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_seen',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
