# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hippie_banevasion', '0007_auto_20170329_0758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='byondversion',
            options={'default_permissions': ('add', 'change', 'delete', 'view')},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'default_permissions': ('add', 'change', 'delete', 'view')},
        ),
        migrations.AlterModelOptions(
            name='clientblob',
            options={'default_permissions': ('add', 'change', 'delete', 'view')},
        ),
        migrations.AlterModelOptions(
            name='useragent',
            options={'default_permissions': ('add', 'change', 'delete', 'view')},
        ),
        migrations.AlterField(
            model_name='client',
            name='byond_versions',
            field=models.ManyToManyField(to='hippie_banevasion.ByondVersion'),
        ),
    ]