# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-13 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hippie_banevasion', '0008_auto_20170911_0141'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
            ],
            options={
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.IntegerField()),
                ('data', models.TextField()),
            ],
            options={
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.AlterField(
            model_name='client',
            name='byond_versions',
            field=models.ManyToManyField(to='hippie_banevasion.ByondVersion'),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hippie_banevasion.Client'),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='ip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hippie_banevasion.IPAddress'),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='useragent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hippie_banevasion.Useragent'),
        ),
        migrations.AddField(
            model_name='client',
            name='ips',
            field=models.ManyToManyField(to='hippie_banevasion.IPAddress'),
        ),
    ]
