# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hippie_banevasion', '0009_auto_20170913_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityevent',
            name='method',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='securityevent',
            name='url',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='byond_versions',
            field=models.ManyToManyField(to='hippie_banevasion.ByondVersion'),
        ),
    ]
