# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hippie_banevasion', '0010_auto_20170913_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityevent',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='byond_versions',
            field=models.ManyToManyField(to='hippie_banevasion.ByondVersion'),
        ),
    ]
