# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hippie_ss13', '0001_initial'),
        ('hippie_banevasion', '0011_auto_20170913_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ['-last_seen']},
        ),
        migrations.AlterField(
            model_name='client',
            name='byond_versions',
            field=models.ManyToManyField(to='hippie_banevasion.ByondVersion'),
        ),
    ]
